elasticsearch:
  builtin:
    enabled: true
  remote:
    host: Unset
  data:
    size: 20Gi
disk:
  storageclass: local-storage
  accessmode: ReadWriteOnce
nginx:
  username: wazuh
  tls: false
  certArn: Unset
versions:
  imagesource: wazuh
  wazuh: 3.12.3_7.6.2
  nginx: 3.12.3_7.6.2
  kibana: 3.12.3_7.6.2
  elasticsearch: 7.6.2
wazuhmaster:
  data:
    size: 20Gi
wazuhworker:
  data:
    size: 20Gi
