apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-nginx
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-nginx
  template:
    metadata:
      labels:
        app: wazuh-nginx
      name: wazuh-nginx
    spec:
      containers:
        - name: wazuh-nginx
          image: {{ printf "%s/wazuh-nginx:%s" .Values.versions.imagesource .Values.versions.nginx }}
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: NGINX_PORT
              value: {{ .Values.nginx.port }}
            - name: NGINX_NAME
              value: {{ .Values.nginx.username }}
            - name: NGINX_PWD
              valueFrom:
                secretKeyRef:
                  name: wazuh-nginx
                  key: NGINX_PWD
          ports:
            - containerPort: 80
            - containerPort: 443
