apiVersion: v1
kind: Secret
metadata:
  name: wazuh-nginx
  namespace: wazuh
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/resource-policy: delete
type: Opaque
data:
  NGINX_PWD: {{ randAlphaNum 16 }}
